[project]
name = "game-operator"
version = "0.1.0"
description = "A Kubernetes operator for managing game servers."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kopf>=1.39.1",
    "kubernetes>=34.1.0",
]
